In [215]:
import pandas as pd
import numpy as np
import ast

In [216]:
movies = pd.read_csv('movies_df.csv')

In [217]:
movies.head(5)

,Unnamed: 0,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [218]:
movies.drop(columns=['Unnamed: 0'],inplace = True)

## Summary

The dataset contains information about **4,809 movies** with **24 features** related to movie details, financial performance, ratings, and production information. The attributes include movie budget, revenue, genres, popularity, cast, crew, release date, runtime, vote average, and vote count. It also contains textual information such as overviews, taglines, keywords, and production details. Most movies in the dataset are in English, and the dataset combines both numerical and categorical data, making it suitable for exploratory data analysis, recommendation systems, sentiment analysis, and movie success prediction.

## Column Description

* `genres`: The category or categories the film falls into (e.g., Action, Science Fiction)
* `homepage`: The URL to the official website of the movie.
* `id`: A unique numerical identifier for the movie (usually from The Movie Database - TMDB).
* `keywords`: Specific words or short phrases that describe the movie's themes, plot, or setting.
* `original_language`: The primary language the film was originally shot and released in (e.g., 'en' for English).
* `original_title`: The native title of the movie before any regional translations.
* `overview`: A brief text summary or synopsis of the movie's plot.
* `popularity`: A metric scoring the movie's cultural footprint and web traffic based on audience engagement.
* `production_companies`: The production studios or companies that funded and created the movie.
* `production_countries`: The countries where the movie was officially produced.
* `release_date`: The date the movie was first released to the public.
* `revenue`: The total worldwide box office earnings generated by the movie (in USD).
* `runtime`: The total length or duration of the movie in minutes.
* `spoken_languages`: The specific languages that are spoken by characters within the film.
* `status`: The current release status of the film (e.g., "Released", "Post Production", or "Rumored").
* `tagline`: The promotional catchphrase or marketing slogan used for the movie.
* `title`: The commonly used (often English) title of the movie.
* `vote_average`: The average rating given by viewers, typically on a scale from 0 to 10.
* `vote_count`: The total number of individual user votes or ratings the movie received.
* `movie_id`: A duplicate or secondary unique identifier (often used as a key to merge with other datasets like cast/crew).
* `cast`: A detailed list of the actors in the film and the specific characters they played.
* `crew`: A detailed list of the behind-the-scenes personnel (directors, writers, producers, etc.) and their specific jobs.

In [219]:
movies.to_excel('movies_df_exported.xlsx', index=False)

## Columns to include
1. `genres`
2. `id`
3. `keywords`
4. `overview`
5. `title`
6. `cast`
7. `crew`

In [220]:
movies = movies[['genres','id','keywords','overview','title','cast','crew']]

In [221]:
movies.head()

,genres,id,keywords,overview,title,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

## Issues with the Dataset

1. Dirty Data
* `genres`,`crew`,`cast`,`keywords` has empty list [] is some of their rows
* `overview` column has 3 missing value
* `genres`,`keywords`,`cast`,`crew` = contains string of list of dictonaries which may create problem
* `overview` is in string , will have to convert it into lsit

2. Messy Data
* Some of the person's first name is same in `cast` and `crew`
*

In [222]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4809 non-null   object
 1   id        4809 non-null   int64
 2   keywords  4809 non-null   object
 3   overview  4806 non-null   object
 4   title     4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [223]:
movies.isna().sum()

genres      0
id          0
keywords    0
overview    3
title       0
cast        0
crew        0
dtype: int64

In [224]:
movies_df = movies.copy()

In [225]:
#dropping all the duplicate values
movies_df.dropna(inplace = True)

## genres

In [226]:
movies_df['genres'].head(1)

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: object

In [227]:
#function to extract the genre of the movie
def converter(row):
    l = []
    for i in ast.literal_eval(row):
        l.append(i['name'])
    return l

In [228]:
movies_df['genres'] = movies_df['genres'].apply(converter)

In [229]:
movies_df['genres'].head()

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [230]:
movies_df['keywords'] = movies_df['keywords'].apply(converter)

## cast

In [231]:
#function to fetch top 3 cast members of the movie
def converter(row):
    l = []
    counter = 0
    for i in ast.literal_eval(row):
        if counter != 3:
            l.append(i['name'])
            counter+=1
        else:
            break
    return l

In [232]:
movies_df['cast'] = movies_df['cast'].apply(converter)

In [233]:
movies_df['cast'].head()

0    [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1       [Johnny Depp, Orlando Bloom, Keira Knightley]
2        [Daniel Craig, Christoph Waltz, Léa Seydoux]
3        [Christian Bale, Michael Caine, Gary Oldman]
4      [Taylor Kitsch, Lynn Collins, Samantha Morton]
Name: cast, dtype: object

## Crew

In [234]:
#function to extract the name of director 
def converter(row):
    l = []
    for i in ast.literal_eval(row):
        if i['job'] == 'Director':
            return i['name']
    return l

In [235]:
movies_df['crew'] = movies_df['crew'].apply(converter)

In [236]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4806 non-null   object
 1   id        4806 non-null   int64
 2   keywords  4806 non-null   object
 3   overview  4806 non-null   object
 4   title     4806 non-null   object
 5   cast      4806 non-null   object
 6   crew      4806 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.4+ KB

In [237]:
movies_df['overview'] = movies_df['overview'].apply(lambda x:x.split())

In [238]:
movies_df.head(5)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",James Cameron
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",Gore Verbinski
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...",Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",Sam Mendes
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",Christopher Nolan
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",Andrew Stanton

In [239]:
#Function to contact the word in given columns
movies_df['cast'] = movies_df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies_df['genres'] = movies_df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies_df['crew'] = movies_df['crew'].str.replace(' ','').apply(lambda x: [x])

In [241]:
movies_df.head(2)

,genres,id,keywords,overview,title,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [243]:
movies_df['tags'] = movies_df['overview']+ movies_df['keywords'] + movies_df['genres'] + movies_df['cast']+ movies_df['crew']

In [245]:
movies_df.head(1)

,genres,id,keywords,overview,title,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [247]:
movies_df = movies_df[['id','tags','title']]

In [250]:
movies_df['tags']=movies_df['tags'].str.join(" ")

/var/folders/77/wyg5lhbd4cb16lv4yrxznbf00000gn/T/ipykernel_21641/2795240451.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['tags']=movies_df['tags'].str.join(" ")

In [252]:
movies_df.head()

,id,tags,title
0,19995,"In the 22nd century, a paraplegic Marine is di...",Avatar
1,285,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,206647,A cryptic message from Bond’s past sends him o...,Spectre
3,49026,Following the death of District Attorney Harve...,The Dark Knight Rises
4,49529,"John Carter is a war-weary, former military ca...",John Carter

In [258]:
movies_df['tags']= movies_df['tags'].apply(lambda x:x.lower() if  isinstance(x,str) else x)

/var/folders/77/wyg5lhbd4cb16lv4yrxznbf00000gn/T/ipykernel_21641/973206714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['tags']= movies_df['tags'].apply(lambda x:x.lower() if  isinstance(x,str) else x)

In [259]:
movies_df.shape

(4806, 3)

In [265]:
movies_df = movies_df.dropna()

In [267]:
movies_df.to_csv('movies_final.csv')